### ISSUE TITLE
compilation issues with meson 0.41.2 stable

### ISSUE THREAD

**Issue by fossfreedom** [budgie-desktop/budgie-desktop#1044]
**Operating System**: ubuntu 17.04
**Budgie version**: git master (19/07/17)

**The issue encountered**

latest stable meson was released today v0.41.2

**raising this here to track those distro's that update to this meson version.**

compilation issues:

```
[125/255] cc  -o src/raven/libraven.so.0.0.0 'src/raven/raven@sha/src_raven_budgie-raven-resources.c.o' 'src/raven/raven@sha/src_plugin_budgie-enums.c.o' 'src/raven/raven@sha/src_raven_raven@sha_calendar.c.o' 'src/raven/raven@sha/src_raven_raven@sha_headerwidget.c.o' 'src/raven/raven@sha/src_raven_raven@sha_main_view.c.o' 'src/raven/raven@sha/src_raven_raven@sha_notifications_view.c.o' 'src/raven/raven@sha/src_raven_raven@sha_powerstrip.c.o' 'src/raven/raven@sha/src_raven_raven@sha_raven.c.o' 'src/raven/raven@sha/src_raven_raven@sha_sound.c.o' 'src/raven/raven@sha/src_raven_raven@sha_MprisClient.c.o' 'src/raven/raven@sha/src_raven_raven@sha_MprisGui.c.o' 'src/raven/raven@sha/src_raven_raven@sha_MprisWidget.c.o' -Wl,--no-undefined -Wl,--as-needed -shared -fPIC -Wl,-soname,libraven.so.0 -g -O2 -fdebug-prefix-map=/home/dad/Downloads/bd-10.3/master/budgie-desktop-10.3.1.0=. -fstack-protector-strong -Wformat -Werror=format-security -Wl,-z,now -Wl,-z,relro src/plugin/libbudgie-plugin.so.0.0.0 -Wl,--start-group src/config/libconfig.a src/lib/libtoplevel.a src/theme/libbudgietheme.so.0.0.0 subprojects/gvc/libgvc.a -lgtk-3 -lgdk-3 -lpangocairo-1.0 -lpango-1.0 -latk-1.0 -lcairo-gobject -lcairo -lgdk_pixbuf-2.0 -lgio-2.0 -lgobject-2.0 -lglib-2.0 -Wl,--end-group -lpeas-1.0 -Wl,--export-dynamic -lgmodule-2.0 -pthread -lgio-2.0 -lgirepository-1.0 -lgobject-2.0 -lglib-2.0 -lgtk-3 -lgdk-3 -lpangocairo-1.0 -lpango-1.0 -latk-1.0 -lcairo-gobject -lcairo -lgdk_pixbuf-2.0 -lgio-2.0 -lgobject-2.0 -lglib-2.0 -lpeas-1.0 -Wl,--export-dynamic -lgmodule-2.0 -pthread -lgio-2.0 -lgirepository-1.0 -lgobject-2.0 -lglib-2.0 -lgtk-3 -lgdk-3 -lpangocairo-1.0 -lpango-1.0 -latk-1.0 -lcairo-gobject -lcairo -lgdk_pixbuf-2.0 -lgio-2.0 -lgobject-2.0 -lglib-2.0 -lpeas-1.0 -Wl,--export-dynamic -lgmodule-2.0 -pthread -lgio-2.0 -lgirepository-1.0 -lgobject-2.0 -lglib-2.0 -lpeas-1.0 -Wl,--export-dynamic -lgmodule-2.0 -pthread -lgio-2.0 -lgirepository-1.0 -lgobject-2.0 -lglib-2.0 -lgtk-3 -lgdk-3 -lpangocairo-1.0 -lpango-1.0 -latk-1.0 -lcairo-gobject -lcairo -lgdk_pixbuf-2.0 -lgio-2.0 -lgobject-2.0 -lglib-2.0 -lm -lpulse -lpulse-mainloop-glib -lpulse -lglib-2.0 '-Wl,-rpath,$ORIGIN/:$ORIGIN/../plugin:$ORIGIN/../theme' -Wl,-rpath-link,/home/dad/Downloads/bd-10.3/master/budgie-desktop-10.3.1.0/debian/build/src/raven:/home/dad/Downloads/bd-10.3/master/budgie-desktop-10.3.1.0/debian/build/src/plugin:/home/dad/Downloads/bd-10.3/master/budgie-desktop-10.3.1.0/debian/build/src/theme  
FAILED: src/raven/libraven.so.0.0.0 
cc  -o src/raven/libraven.so.0.0.0 'src/raven/raven@sha/src_raven_budgie-raven-resources.c.o' 'src/raven/raven@sha/src_plugin_budgie-enums.c.o' 'src/raven/raven@sha/src_raven_raven@sha_calendar.c.o' 'src/raven/raven@sha/src_raven_raven@sha_headerwidget.c.o' 'src/raven/raven@sha/src_raven_raven@sha_main_view.c.o' 'src/raven/raven@sha/src_raven_raven@sha_notifications_view.c.o' 'src/raven/raven@sha/src_raven_raven@sha_powerstrip.c.o' 'src/raven/raven@sha/src_raven_raven@sha_raven.c.o' 'src/raven/raven@sha/src_raven_raven@sha_sound.c.o' 'src/raven/raven@sha/src_raven_raven@sha_MprisClient.c.o' 'src/raven/raven@sha/src_raven_raven@sha_MprisGui.c.o' 'src/raven/raven@sha/src_raven_raven@sha_MprisWidget.c.o' -Wl,--no-undefined -Wl,--as-needed -shared -fPIC -Wl,-soname,libraven.so.0 -g -O2 -fdebug-prefix-map=/home/dad/Downloads/bd-10.3/master/budgie-desktop-10.3.1.0=. -fstack-protector-strong -Wformat -Werror=format-security -Wl,-z,now -Wl,-z,relro src/plugin/libbudgie-plugin.so.0.0.0 -Wl,--start-group src/config/libconfig.a src/lib/libtoplevel.a src/theme/libbudgietheme.so.0.0.0 subprojects/gvc/libgvc.a -lgtk-3 -lgdk-3 -lpangocairo-1.0 -lpango-1.0 -latk-1.0 -lcairo-gobject -lcairo -lgdk_pixbuf-2.0 -lgio-2.0 -lgobject-2.0 -lglib-2.0 -Wl,--end-group -lpeas-1.0 -Wl,--export-dynamic -lgmodule-2.0 -pthread -lgio-2.0 -lgirepository-1.0 -lgobject-2.0 -lglib-2.0 -lgtk-3 -lgdk-3 -lpangocairo-1.0 -lpango-1.0 -latk-1.0 -lcairo-gobject -lcairo -lgdk_pixbuf-2.0 -lgio-2.0 -lgobject-2.0 -lglib-2.0 -lpeas-1.0 -Wl,--export-dynamic -lgmodule-2.0 -pthread -lgio-2.0 -lgirepository-1.0 -lgobject-2.0 -lglib-2.0 -lgtk-3 -lgdk-3 -lpangocairo-1.0 -lpango-1.0 -latk-1.0 -lcairo-gobject -lcairo -lgdk_pixbuf-2.0 -lgio-2.0 -lgobject-2.0 -lglib-2.0 -lpeas-1.0 -Wl,--export-dynamic -lgmodule-2.0 -pthread -lgio-2.0 -lgirepository-1.0 -lgobject-2.0 -lglib-2.0 -lpeas-1.0 -Wl,--export-dynamic -lgmodule-2.0 -pthread -lgio-2.0 -lgirepository-1.0 -lgobject-2.0 -lglib-2.0 -lgtk-3 -lgdk-3 -lpangocairo-1.0 -lpango-1.0 -latk-1.0 -lcairo-gobject -lcairo -lgdk_pixbuf-2.0 -lgio-2.0 -lgobject-2.0 -lglib-2.0 -lm -lpulse -lpulse-mainloop-glib -lpulse -lglib-2.0 '-Wl,-rpath,$ORIGIN/:$ORIGIN/../plugin:$ORIGIN/../theme' -Wl,-rpath-link,/home/dad/Downloads/bd-10.3/master/budgie-desktop-10.3.1.0/debian/build/src/raven:/home/dad/Downloads/bd-10.3/master/budgie-desktop-10.3.1.0/debian/build/src/plugin:/home/dad/Downloads/bd-10.3/master/budgie-desktop-10.3.1.0/debian/build/src/theme  
src/lib/libtoplevel.a(src_lib_toplevel@sta_toplevel.c.o): In function `budgie_toplevel_class_init':
./debian/build/src/lib/toplevel@sta/toplevel.c:464: undefined reference to `budgie_applet_info_get_type'
collect2: error: ld returned 1 exit status
```
 ...

**Steps to reproduce the issue**

use either meson stable v0.41.2 or meson git master
 ...

**Comment by ikeydoherty** [comment]
Looks again to me like a case of "meson broke something" - because that symbol is declared in the `plugin` tree (applet-info.{c,h}) and both Raven + toplevel portions link to it

**Comment by alunux** [comment]
Same report here https://github.com/mesonbuild/meson/issues/1969#issuecomment-313854524

**Comment by fossfreedom** [comment]
@alunux please create a new issue on the meson tracker - that linked issue has been closed.  Ikey's comment above should be added to that new issue.  thanks

**Comment by fossfreedom** [comment]
@ikeydoherty I've done a git bisect on the 0.41 branch - the bad commit landed on this.

Any thoughts why this is impacting on budgie desktop?

```
git bisect bad
ae9b23832e3ef4064e5735265ce7008794ab0491 is the first bad commit
commit ae9b23832e3ef4064e5735265ce7008794ab0491
Author: Nirbheek Chauhan <nirbheek@centricular.com>
Date:   Fri Jun 2 05:25:17 2017 +0530

    ninja: De-dup libraries and use --start/end-group
    
    Now we aggressively de-dup the list of libraries used while linking,
    and when linking with GNU ld we have to enclose all static libraries
    with -Wl,--start-group and -Wl,--end-group to force the linker to
    resolve all symbols recursively. This is needed when static libraries
    have circular deps on each other (see included test).
    
    The --start/end-group change is also needed for circular dependencies
    between static libraries because we no longer recursively list out all
    library dependencies.
    
    The size of build.ninja for GStreamer is now down to 6.1M from 20M,
    and yields a net reduction in configuration time of 10%

:040000 040000 cd66aeea1c147f551ee0e324f789d9b28cdb9f0e bb2d5e9f6af008334ba7ad400abbb9008350972c M	mesonbuild
:100755 100755 e3b7c5cc31141113bd55d2cab16fd5d5888bbb6b 71448f9418b8df4f4444a5345a0bb32634b45bc9 M	run_unittests.py
:040000 040000 4d672ea6e61105790be122ff83243477cb6afa8c 27acf2c7501b230fcdd4a28763e62b18352ebd45 M	test cases
```

**Comment by ikeydoherty** [comment]
The Solus toolchain is modified to **force** the `-Wl,--as-needed` behaviour when `LD_AS_NEEDED=1` in the environment, i.e. during packaging builds, and Budgie still builds fine. If `ld` is already happy with this forced behaviour, they've certainly gotten something wrong upstream.

TBQH I'm about ready to go back to autotools with its warts & whatnot, at least that didn't shit itself on every update and redefine the core behaviour (And assuming us mere mortals should know how meson is meant to work internally when the relevant bits are never documented)

**Comment by fossfreedom** [comment]
k - let me throw this on the meson tracker - hopefully someone will respond

**Comment by ikeydoherty** [comment]
Looks like meson is making some really really naive assumptions about the toolchain too, and really couldn't account for `lld` on clang or `ld.bfd` vs `ld` vs `ld.gold` ..

**Comment by nirbheek** [comment]
Sorry about missing this, it slipped through the cracks because a new issue wasn't filed for it. Otherwise I would've looked into it before the 0.41.2 stable release.

I'm currently trying to figure out how you can do a workaround without waiting for a hotfix to reach distros.

> Looks like meson is making some really really naive assumptions about the toolchain too, and really couldn't account for lld on clang or ld.bfd vs ld vs ld.gold ..

I'm not sure what this means (GNU ld is either bfd or gold, and we do have linker-specific code), but we tested that patch with all those linkers. I missed a specific scenario (static library needing a symbol in a dynamic library and not appearing before the dynamic library in the linker command), but mistakes happen. :)

Relatedly, where do you have CI running for Budgie? It would be great if you could set up one of your jobs to build against meson git master and report any issues to us early. 

Meson is under active development and we are strongly test-driven (we have a *lot* of CI), but the real tests are complex projects (like budgie, gstreamer, systemd) that use it. We already have this for GNOME Continuous and [GStreamer](https://ci.gstreamer.net/job/GStreamer-master-meson/), and it's been very helpful.

**Comment by ikeydoherty** [comment]
> Sorry about missing this

Shit happens - don't panic.

> Relatedly, where do you have CI running for Budgie?

Solus is the CI engine for Budgie, as Travis is honestly too poor to use. We also need more recent library versions than what Travis and alternatives offer (not to mention being bound to broken Ubuntu expectations)

If you know some newer shinier alternatives I'm happy to look into them

**Comment by nirbheek** [comment]
For Meson, we run all our Linux tests inside an Ubuntu docker image on Travis. Perhaps you can try a Debian image or whatever suits you. Alternatively, try to see if you can do a git clone of meson as part of your Solus CI. You don't need to install Meson, just running it from the git checkout is enough.

**Comment by ikeydoherty** [comment]
Docker mightn't be a bad way of going around it, at least then I'll have new shinies to deal with. Obviously Budgie presents a sufficient number of complex weirdities to be of interest to Meson development.
