### ISSUE TITLE
10.3 failed to build on ubuntu 16.10

### ISSUE THREAD

**Issue by fossfreedom** [budgie-desktop/budgie-desktop#862]
**Operating System**: ubuntu 16.10
**Budgie version**: i.e. Budgie 10.3
building on ubuntu 16.10 fails

build log: https://launchpadlibrarian.net/316037123/buildlog_ubuntu-yakkety-amd64.budgie-desktop_10.3-0ubuntu0.2_BUILDING.txt.gz

think this is the relevant build failures:

```
../../src/imports/natray/fixedtip.c: In function ‘get_monitor_geometry’:
../../src/imports/natray/fixedtip.c:134:3: error: unknown type name ‘GdkMonitor’
   GdkMonitor *monitor;
   ^~~~~~~~~~
../../src/imports/natray/fixedtip.c:137:13: error: implicit declaration of function ‘gdk_display_get_monitor_at_window’ [-Werror=implicit-function-declaration]
   monitor = gdk_display_get_monitor_at_window (display, window);
             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../../src/imports/natray/fixedtip.c:137:11: warning: assignment makes pointer from integer without a cast [-Wint-conversion]
   monitor = gdk_display_get_monitor_at_window (display, window);
           ^
../../src/imports/natray/fixedtip.c:139:3: error: implicit declaration of function ‘gdk_monitor_get_geometry’ [-Werror=implicit-function-declaration]
   gdk_monitor_get_geometry (monitor, geometry);
   ^~~~~~~~~~~~~~~~~~~~~~~~
```

thoughts?

**Comment by rilian-la-te** [comment]
What GTK version ubuntu 16.10 have? GdkMonitor is 3.22 only thing, AFAIK.

**Comment by fossfreedom** [comment]
Gtk+3.20

**Comment by rilian-la-te** [comment]
There is a cause. 10.3 requires 3.22.

**Comment by fossfreedom** [comment]
Does 10.3 specifically need the 3.22 version of natray or can i substitute it for the 10.2.9 version of natray?

**Comment by ikeydoherty** [comment]
You'd need to restore the older tray applet too, I didn't realise I'd introduced 3.22 specifics, sorry. I'll get a patch together just after the Solus release

**Comment by ikeydoherty** [comment]
Stupid github issue closer..

OK @fossfreedom this should fix it - please try

**Comment by fossfreedom** [comment]
thanks @ikeydoherty 

its now passed that bit of the code.

Compilation now fails here:

```
[182/221] valac '-d' 'src/wm/budgie-wm@exe' '-C' '--pkg' 'libmutter' '--pkg' 'gnome-desktop-3.0' '--pkg' 'gsettings-desktop-schemas' '--pkg' 'ibus-1.0' '--pkg' 'gio-unix-2.0' '--pkg' 'ibus-1.0' '--pkg' 'gnome-desktop-3.0' '--pkg' 'libmutter' '--pkg' 'budgie-config' '--pkg' 'gsettings-desktop-schemas' '--vapidir' '/<<PKGBUILDDIR>>/vapi' '--vapidir' '/<<PKGBUILDDIR>>/src/config' '' ../../src/wm/background.vala ../../src/wm/ibus.vala ../../src/wm/keyboard.vala ../../src/wm/main.vala ../../src/wm/shim.vala ../../src/wm/wm.vala
FAILED: src/wm/budgie-wm@exe/background.c src/wm/budgie-wm@exe/ibus.c src/wm/budgie-wm@exe/keyboard.c src/wm/budgie-wm@exe/main.c src/wm/budgie-wm@exe/shim.c src/wm/budgie-wm@exe/wm.c 
valac '-d' 'src/wm/budgie-wm@exe' '-C' '--pkg' 'libmutter' '--pkg' 'gnome-desktop-3.0' '--pkg' 'gsettings-desktop-schemas' '--pkg' 'ibus-1.0' '--pkg' 'gio-unix-2.0' '--pkg' 'ibus-1.0' '--pkg' 'gnome-desktop-3.0' '--pkg' 'libmutter' '--pkg' 'budgie-config' '--pkg' 'gsettings-desktop-schemas' '--vapidir' '/<<PKGBUILDDIR>>/vapi' '--vapidir' '/<<PKGBUILDDIR>>/src/config' '' ../../src/wm/background.vala ../../src/wm/ibus.vala ../../src/wm/keyboard.vala ../../src/wm/main.vala ../../src/wm/shim.vala ../../src/wm/wm.vala
error:  not found
Compilation failed: 1 error(s), 0 warning(s)
```

That just looks strange "src/wm/budgie-wm@exe" - what is valac doing here?  anything to-do with the package GTK+3.22 libmutter-dev rather than the GTK+3.24 libmutter0-dev ?

https://launchpadlibrarian.net/316047660/buildlog_ubuntu-yakkety-i386.budgie-desktop_10.3-0ubuntu0.3_BUILDING.txt.gz

**Comment by ikeydoherty** [comment]
Two more fixes added @fossfreedom

**Comment by ikeydoherty** [comment]
@fossfreedom I'm going to be tagging 10.3.1 as soon as @cybre's pull request comes through and lands, as it's going into the Solus release. Ideally I would like to know this is fixed before then.

**Comment by fossfreedom** [comment]
excellent - all builds (with the latest commit) build ok on 16.04 / 16.10 and of-course 17.04.

cheers ikey.

**Comment by ikeydoherty** [comment]
That's what I like to hear :) I'll pop out a point release once you've got some more testing done
